# На какой группе серверов
- hosts: webservers

  tasks:
    - name: remove git
      ansible.builtin.apt: # имя модуля Ansible
        name: git
        state: absent
      become: yes
#      become_user: admin
