# На какой группе серверов
- hosts: webservers

  tasks:

    - name: Update apt cache
      # apt-get update
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
      become: yes
      tags: nodejs

    - name: Add the user 'arya' with a specific uid and a primary group of 'developer'
      ansible.builtin.user:
        name: arya
        uid: 1040
      become: yes
      tags: new_user
